// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyzznvWBVRsUoCIvE0HyRKHJROWIyr_pQ',
    appId: '1:968999252029:web:f128eb84ade78c48a53a54',
    messagingSenderId: '968999252029',
    projectId: 'employeeattendanceapp-a6146',
    authDomain: 'employeeattendanceapp-a6146.firebaseapp.com',
    storageBucket: 'employeeattendanceapp-a6146.firebasestorage.app',
    measurementId: 'G-H4CT1ZF149',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABQtiz0hhRWxJ-6UtSu4Vb5cFNXhMtVyE',
    appId: '1:968999252029:android:7d20f95841130a71a53a54',
    messagingSenderId: '968999252029',
    projectId: 'employeeattendanceapp-a6146',
    storageBucket: 'employeeattendanceapp-a6146.firebasestorage.app',
  );
}
